# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooktrend',
            name='link',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twittertrend',
            name='link',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
