# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0003_auto_20170523_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookTrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=160)),
                ('created', models.DateTimeField(verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterTrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('link', models.CharField(max_length=500)),
                ('created', models.DateTimeField(verbose_name='created')),
            ],
        ),
    ]
