# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_facebooktrend_twittertrend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooktrend',
            name='created',
            field=models.DateTimeField(null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='twittertrend',
            name='created',
            field=models.DateTimeField(null=True, verbose_name='created'),
        ),
    ]
