# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20170523_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooktrend',
            name='created',
            field=models.DateTimeField(default=True, verbose_name=datetime.datetime(2017, 5, 23, 14, 21, 21, 617532)),
        ),
        migrations.AlterField(
            model_name='twittertrend',
            name='created',
            field=models.DateTimeField(default=True, verbose_name=datetime.datetime(2017, 5, 23, 14, 21, 21, 616802)),
        ),
    ]
