# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20170523_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooktrend',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 23, 14, 23, 39, 558577)),
        ),
        migrations.AlterField(
            model_name='twittertrend',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 23, 14, 23, 39, 557872)),
        ),
    ]
