# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20170523_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooktrend',
            name='created',
            field=models.DateTimeField(default=0, verbose_name=datetime.datetime(2017, 5, 23, 19, 26, 36, 630812, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twittertrend',
            name='created',
            field=models.DateTimeField(default=0, verbose_name=datetime.datetime(2017, 5, 23, 19, 26, 36, 630226, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
