# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20170523_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooktrend',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 23, 19, 30, 6, 741790, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='twittertrend',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 23, 19, 30, 6, 741190, tzinfo=utc)),
        ),
    ]
