# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20170523_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooktrend',
            name='created',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2017, 5, 23, 14, 50, 59, 331912)),
        ),
        migrations.AlterField(
            model_name='twittertrend',
            name='created',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2017, 5, 23, 14, 50, 59, 331282)),
        ),
    ]
