# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_auto_20170523_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooktrend',
            name='created',
            field=models.DateTimeField(verbose_name=b'2017-05-23 14:56:46.861952'),
        ),
        migrations.AlterField(
            model_name='twittertrend',
            name='created',
            field=models.DateTimeField(verbose_name=b'2017-05-23 14:56:46.861952'),
        ),
    ]
