# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_auto_20170523_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooktrend',
            name='created',
            field=models.DateTimeField(verbose_name=b'2017-05-23 15:00:36.064256'),
        ),
        migrations.AlterField(
            model_name='twittertrend',
            name='created',
            field=models.DateTimeField(verbose_name=b'2017-05-23 15:00:36.063521'),
        ),
    ]
